spring:
  datasource:
    url: jdbc:mysql://localhost:3306/educationdb
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    root: warn
    it:
      naveen: trace
educationapp:
  version: 1.0
  corsconfig:
    allowedorgin: '*'
    allowedmethods: GET,POST,PUT,PATCH,DELETE,HEAD
    allowedcredentials: false
    maxage: 3600
  swagger:
    enabled: true
    title: Education App Api
    description: Education App Api
    useDefaultResponseMessages: false
    enableUrlTemplating: false
    deepLinking: true
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 1
    displayOperationId: false
    displayRequestDuration: false
    filter: false
    maxDisplayedTags: 0
    showExtensions: false

